-- public.contracts definition

-- Drop table

-- DROP TABLE public.contracts;

CREATE TABLE public.contracts (
	id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	contract_num varchar(20) NULL,
	r_body jsonb NULL,
	xml_body xml NULL,
	hash varchar(64) NULL,
	type_contract varchar(64) NULL,
	zip_file varchar(256) NULL,
	file_name varchar(128) NULL,
	fz_type int2 NOT NULL,
	publish_date timestamp NOT NULL,
	CONSTRAINT pk_contracts PRIMARY KEY (id)
);
CREATE UNIQUE INDEX i_contracts_hash_idx ON public.contracts USING btree (hash);

-- public.file_cashes definition

-- Drop table

-- DROP TABLE public.file_cashes;

CREATE TABLE public.file_cashes (
	id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	zip_file varchar(128) NULL,
	full_path varchar(256) NULL,
	base_dir varchar(64) NULL,
	dirtype varchar(64) NULL,
	"date" timestamptz NOT NULL,
	"size" int8 NOT NULL,
	status int4 NOT NULL,
	fz_type int4 NOT NULL,
	modifid_date timestamptz NOT NULL,
	CONSTRAINT pk_file_cashes PRIMARY KEY (id)
);


-- public.notifications definition

-- Drop table

-- DROP TABLE public.notifications;

CREATE TABLE public.notifications (
	id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	purchase_num varchar(20) NULL,
	protocol_num varchar(100) NULL,
	r_body jsonb NULL,
	inn varchar(12) NULL,
	wname varchar(1024) NULL,
	participant_info jsonb NULL,
	app_rating int2 NOT NULL,
	contract_conclusion_on_st83ch2 bool NOT NULL,
	journal_number varchar(100) NULL,
	w_price numeric(18, 2) NOT NULL,
	hash varchar(64) NULL,
	type_notif varchar(64) NULL,
	zip_file varchar(256) NULL,
	file_name varchar(128) NULL,
	fz_type int2 NOT NULL,
	protocol_date timestamp NOT NULL,
	publish_date timestamp NOT NULL,
	CONSTRAINT pk_notifications PRIMARY KEY (id)
);
CREATE UNIQUE INDEX i_notifications_hash_idx ON public.notifications USING btree (hash);

-- public.nsi_a_reasons definition

-- Drop table

-- DROP TABLE public.nsi_a_reasons;

CREATE TABLE public.nsi_a_reasons (
	id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	oos_id int8 NOT NULL,
	code varchar(20) NULL,
	"name" varchar(3000) NULL,
	object_name varchar(350) NULL,
	"type" varchar(4) NULL,
	doc_type jsonb NULL,
	placing_way jsonb NULL,
	actual bool NOT NULL,
	fz_type int4 NOT NULL,
	CONSTRAINT pk_nsi_a_reasons PRIMARY KEY (id)
);

-- public.nsi_etps definition

-- Drop table

-- DROP TABLE public.nsi_etps;

CREATE TABLE public.nsi_etps (
	id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	code varchar(20) NULL,
	"name" varchar(200) NULL,
	description varchar(200) NULL,
	phone varchar(30) NULL,
	address varchar(50) NULL,
	email varchar(50) NULL,
	full_name varchar(2000) NULL,
	inn varchar(10) NULL,
	kpp varchar(9) NULL,
	actual bool NOT NULL,
	CONSTRAINT pk_nsi_etps PRIMARY KEY (id)
);


-- public.nsi_file_cashes definition

-- Drop table

-- DROP TABLE public.nsi_file_cashes;

CREATE TABLE public.nsi_file_cashes (
	id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	zip_file varchar(128) NULL,
	full_path varchar(256) NULL,
	base_dir varchar(64) NULL,
	dirtype varchar(64) NULL,
	"date" timestamptz NOT NULL,
	"size" int8 NOT NULL,
	status int4 NOT NULL,
	fz_type int4 NOT NULL,
	modifid_date timestamptz NOT NULL,
	CONSTRAINT pk_nsi_file_cashes PRIMARY KEY (id)
);

-- public.nsi_organizations definition

-- Drop table

-- DROP TABLE public.nsi_organizations;

CREATE TABLE public.nsi_organizations (
	id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	reg_number varchar(20) NULL,
	full_name varchar(2000) NULL,
	nsi_data jsonb NULL,
	accounts jsonb NULL,
	registration_date timestamptz NOT NULL,
	inn varchar(10) NULL,
	kpp varchar(20) NULL,
	ogrn varchar(20) NULL,
	is_actual bool NOT NULL,
	fz_type int4 NOT NULL,
	change_esia_date_time timestamptz NOT NULL DEFAULT '-infinity'::timestamp without time zone,
	CONSTRAINT pk_nsi_organizations PRIMARY KEY (id)
);
CREATE INDEX i_nsi_organizations_idx ON public.nsi_organizations USING btree (reg_number, fz_type);

-- public.nsi_placing_ways definition

-- Drop table

-- DROP TABLE public.nsi_placing_ways;

CREATE TABLE public.nsi_placing_ways (
	id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	placing_way_id int8 NOT NULL,
	placing_way_data jsonb NULL,
	code varchar(20) NULL,
	"name" varchar(3000) NULL,
	ss_type int4 NOT NULL,
	"type" varchar(20) NULL,
	fz_type int4 NOT NULL,
	actual bool NOT NULL,
	is_procedure bool NOT NULL,
	is_exclude bool NOT NULL,
	is_closing bool NOT NULL,
	CONSTRAINT pk_nsi_placing_ways PRIMARY KEY (id)
);

-- public.protocols definition

-- Drop table

-- DROP TABLE public.protocols;

CREATE TABLE public.protocols (
	id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	purchase_num varchar(20) NULL,
	protocol_num varchar(100) NULL,
	r_body jsonb NULL,
	hash varchar(64) NULL,
	type_protocol varchar(64) NULL,
	zip_file varchar(256) NULL,
	file_name varchar(128) NULL,
	fz_type int2 NOT NULL,
	publish_date timestamp NOT NULL,
	CONSTRAINT pk_protocols PRIMARY KEY (id)
);
CREATE UNIQUE INDEX i_protocols_idx ON public.protocols USING btree (hash);

--CREATE UNIQUE INDEX i_contracts_hash_idx ON public.contracts USING btree (hash);
--CREATE UNIQUE INDEX i_notifications_hash_idx ON public.notifications USING btree (hash);
--CREATE INDEX i_nsi_organizations_idx ON public.nsi_organizations USING btree (reg_number, fz_type);
--CREATE UNIQUE INDEX i_protocols_idx ON public.protocols USING btree (hash);
--CREATE UNIQUE INDEX i_contract_projects_idx ON public.contract_projects USING btree (hash);